db:
  image: mdillon/postgis
redis:
  image: redis:3.0.3
citygram:
  image: citygram:latest
  env_file: .env.sample
  environment:
    DB_NAME: citygram_development
    PG_USER: postgres
    PG_HOST: citygram_db_1
    DATABASE_URL: postgres://postgres@citygram_db_1/citygram_development
  command: bundle exec foreman start
  volumes:
    - .:/usr/src/app/citygram
  ports:
    - "9292:9292"
  links:
    - db
    - redis
